# Generated by Django 3.2.4 on 2021-06-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaper', '0002_alter_paper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='marks',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
