# Generated by Django 3.2.4 on 2021-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaper', '0005_auto_20210626_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
