# Generated by Django 3.2.4 on 2021-06-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210623_0009'),
        ('questions', '0007_auto_20210623_1650'),
    ]

    operations = [
    ]
