# Generated by Django 3.2.4 on 2021-06-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20210626_2026'),
        ('questions', '0011_alter_question_text'),
    ]

    operations = [
    ]
