# Generated by Django 3.2.5 on 2021-07-11 08:02

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='chapter', chained_model_field='chapter', on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='questions.topic'),
        ),
    ]
