# Generated by Django 3.2.5 on 2021-07-11 08:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='standard', chained_model_field='standard', on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='questions.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='questions.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='standard', chained_model_field='standard', on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='questions.subject'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='questions.chapter'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='standard', chained_model_field='standard', on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='questions.subject'),
        ),
    ]
