# Generated by Django 3.2.5 on 2021-07-23 11:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=tinymce.models.HTMLField(),
        ),
    ]
