# Generated by Django 3.2.5 on 2021-10-22 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_auto_20211022_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
