# Generated by Django 3.2.5 on 2021-10-22 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20211022_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
