# Generated by Django 3.2.5 on 2021-10-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_auto_20211022_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
