# Generated by Django 3.2.5 on 2021-12-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20211022_2217'),
        ('questions', '0032_auto_20211022_2328'),
    ]

    operations = [
    ]
