# Generated by Django 3.2.5 on 2021-12-13 05:12

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_solution_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='option',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='question', chained_model_field='question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Solution', to='questions.option'),
        ),
    ]
