# Generated by Django 3.2.5 on 2021-12-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0035_alter_solution_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='option',
            field=models.CharField(choices=[('basic', 'basic'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default=3, max_length=100),
            preserve_default=False,
        ),
    ]
