# Generated by Django 3.2.5 on 2021-12-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_alter_solution_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='option',
        ),
    ]
