# Generated by Django 3.2.5 on 2021-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_remove_solution_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='option',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=100, null=True),
        ),
    ]
