# Generated by Django 3.2.5 on 2021-12-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_auto_20211213_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='for_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
