# Generated by Django 3.2.5 on 2022-05-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_question_for_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='for_quiz',
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, default='Yes', max_length=500, null=True),
        ),
    ]
