# Generated by Django 3.2.4 on 2021-06-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_question', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
