# Generated by Django 3.2.5 on 2021-07-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transactions_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
