"""
Django settings for rancikeCms project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6%rg!q(=8z)-6+&#_4$08jvkew$gsbk00mlaxlsu290gt14_pa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'main',
    'register_login',
    'social_django',
    'widget_tweaks',
    'upload_question',
    'questions',
    'generatePDF',
    'SchoolDashboard',
    'tinymce',
    'QuestionPaper',
    'orders',
    'payment',
    'TeacherDashboard',
    'smart_selects',
    'meta',  # maintian this at the end
    'django_cleanup.apps.CleanupConfig',  # place last to avoid conflicting signals
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
]

ROOT_URLCONF = 'rancikeCms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rancikeCms.context_processors.total_items_in_cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'rancikeCms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
#


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


# Social Auths
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '653650831518-ig1dm8llb40asrq6ik6u32alhdsjlhf9.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '6UU2L5hHTbfxm_t41rsRnog6'
LOGIN_URL = '/auth/login/google-oauth2/'
SOCIAL_AUTH_URL_NAMESPACE = 'social'

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'media/emails')
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'edulearning098@gmail.com'
EMAIL_HOST_PASSWORD = 'rkuyegeltttbbvln'

# register_login
AUTH_USER_MODEL = 'register_login.User1'

ENABLE_USER_ACTIVATION = True
DISABLE_USERNAME = False
LOGIN_VIA_EMAIL = True
LOGIN_VIA_EMAIL_OR_USERNAME = False
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'accounts:log_in'
USE_REMEMBER_ME = True

RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME = False
ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE = True

DISABLE_USERNAME = True
SIGN_UP_FIELDS = ['username', 'first_name', 'last_name',
                  'school_name', 'location', 'email', 'password1', 'password2']
if DISABLE_USERNAME:
    SIGN_UP_FIELDS = ['first_name', 'last_name', 'school_name',
                      'location', 'email', 'password1', 'password2']


# Meta
META_USE_TITLE_TAG = True
META_SITE_PROTOCOL = 'https'
META_USE_OG_PROPERTIES = True
META_SITE_DOMAIN = 'onlinekitabghar.in'
META_DEFAULT_IMAGE = "https://onlinekitabghar.in/static/images/logo.png"
META_INCLUDE_KEYWORDS = ['Kitab Ghar',
                         'KitabGhar',
                         'Punjab',
                         'Culture',
                         'India',
                         'international',
                         'Novels',
                         'Books',
                         'Biography',
                         'Poetry',
                         'stories',
                         'Blogs',
                         'punjab',
                         'Ravinder Singh',
                         'Tradition',
                         'payumoney',
                         ]

BASE_URL = ""
if DEBUG:
    BASE_URL = 'http://127.0.0.1:8000'
else:
    BASE_URL = 'https://cms.rancikelearning.com'



TINYMCE_COMPRESSOR = False


TINYMCE_DEFAULT_CONFIG = {
    'cleanup_on_startup': False,
    'height': 500,
    'trim_span_elements': False,
    'verify_html': False,
    'cleanup': False,
    'custom_undo_redo_levels': 50,
    'encoding': "utf-8",
    'selector': 'textarea',
    'theme': 'silver',
    'images_upload_url': BASE_URL+'/upload_question/upload_image/',
    'convert_urls': False,
    'external_plugins': {'tiny_mce_wiris': 'https://www.wiris.net/demo/plugins/tiny_mce/plugin.js'},
    'plugins': '''
            textcolor save link file image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link | charmap |  code |
            ''',
    'toolbar2': '''
             image | tiny_mce_wiris_formulaEditor | tiny_mce_wiris_formulaEditorChemistry |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}


USE_DJANGO_JQUERY = True

PAYTM_MERCHANT_ID = 'BqOyfu71153778401294'
PAYTM_SECRET_KEY = 'Ol9vkXVntX8etf6h'
PAYTM_WEBSITE = 'WEBSTAGING'
PAYTM_CHANNEL_ID = 'WEB'
PAYTM_INDUSTRY_TYPE_ID = 'Retail'


COST_PER_QUESTION = 1

